{{- if and .Values.rbac.enabled .Values.rbac.role.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ .Chart.Name }}-scc
  resources:
  - SecurityContextConstraints
  verbs:
  - use

{{- end }}