{{- if and .Values.rbac.enabled .Values.rbac.roleBinding.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-sa

{{- end }}