portal-dashboard:
  enabled: true
  replicaCount: 1
  image:
    repository: "quay.io/zagaos/zagaobserve-portal-dashboard"
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  route:
    subdomain: portal-dashboard
    enabled: true



  dashboard:
    enabled: true
