apiVersion: v2
name: infra
description: A Helm chart for Kubernetes

version: 1.0.0

dependencies:

- name: infra-ingestion-node
  version: "1.0.0"
  repository: "file://charts/infra-ingestion-node"
  condition: subcharts.infra-ingestion-node
  tags:
  - infra-ingestion-node

- name: infra-ingestion-pod
  version: "1.0.0"
  repository: "file://charts/infra-ingestion-pod"
  condition: subcharts.infra-ingestion-pod
  tags:
  - infra-ingestion-pod

- name: infra-ingestion-events
  version: "1.0.0"
  repository: "file://charts/infra-ingestion-events"
  condition: subcharts.infra-ingestion-events
  tags:
  - infra-ingestion-events

- name: infra-query-api
  version: "1.0.0"
  repository: "file://charts/infra-query-api"
  condition: subcharts.infra-query-api
  tags:
  - infra-query-api

- name: infra-dashboard
  version: "1.0.0"
  repository: "file://charts/infra-dashboard"
  condition: subcharts.infra-dashboard
  tags:
  - infra-dashboard
