rbac:
  enabled: true

  serviceAccount:
    create: true
    annotations: {}

  role:
    create: true
    annotations: {}

  roleBinding:
    create: true
    annotations: {}
  
  scc:
    create: true

###################

coordinator:
  enabled: true
worker:
  enabled: true

###################

trino-coordinator:

  replicaCount: 1

  image:
    repository: "quay.io/osclimate/trino"
    tag: "latest"
    pullPolicy: IfNotPresent

  strategy: 
    type: Recreate

  service:
    type: ClusterIP

  route:
    subdomain: trino-coordinator

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

  configmapEnv:
    data:
      HIVE_DB_EXTERNAL: "true"
      S3_ENDPOINT_URL: http://minio-dev.$(NAMESPACE).svc.cluster.local:9000
      S3_PREFIX: data
      S3_BUCKET: zaga
      DATABASE_HOST: hive-postgresql
      DATABASE_PORT: "5432"

  secretEnv:
    data:
      AWS_ACCESS_KEY_ID: minioAdmin
      AWS_SECRET_KEY_ID: admin1234
      INTER_COMM_SHARED_SECRET: kzs71nsYBRr8cysT62zb6P+VT8YsVi/eASfNKUJkvPDce6aof6FLyM/0EDA8qK46P8sD2jXBTTe7cKX0MEqTS2UNZ7YdYWHUUoSG2nLgEryZbqlEkguYWs2dSSYkzv9DIPMtRvGxmNdQ6HGGscrqsFkeK7kSCd6mn5YNskIv6Z665gquqq+SlqV5UylFDcXhB6Z7oWuZ2fq3WONVWtTIhYP73YO8iDORG2afkqPQhRKTw848YQVrcqKAIOX6sirMb5KE1BP0yXz533J71vFuMqkvTBrFV3lkvAq+/7W4iA9Xn9WDJ8TGgcwB7jFOLH9htKYrXtO2XgMsWxizi7XbFzXsPEreqndhZEX7i6U0/K22kCWRy7/lcH+JMQAzq3J+qxl1KqTLVTfu3iSIKUj093/wR0EPcH282a+HMzk/5E1aGk3uV40M/1wQwlEDzBRaGtLtW7tyFHX+sc29nLgkOFAPknwqnYoSR7FDEgO+CrB00zNeY1lS1Xx8OCEfGgg+y5zK7pSMm7cuq8PHjENXCsWOY3xNkJLKsf9mWiWLZhxE1G6EQMG8WPz2r+DhBskTaoHaRPCfcD3/2vaDEjvfK/9kek94g00JcjJB9HQQe3tINmEBxkA8SjIWZe40kcPU0hbKqeA8WFzUgwsB/2KxFvTcPpRvNKseozZZxL/2Dlk=
    type: Opaque


  catalogs:
    data:
      - name: hive.properties
        path: configs/trino-catalog/hive.properties
      - name: iceberg.properties
        path: configs/trino-catalog/iceberg.properties
      - name: tpcds.properties
        path: configs/trino-catalog/tpcds.properties
      - name: tpch.properties
        path: configs/trino-catalog/tpch.properties

  configs:
    data:
      - name: config.properties
        path: configs/trino-coordinator/config.properties
      - name: exchange-manager.properties
        path: configs/trino-coordinator/exchange-manager.properties
      - name: group-mapping.properties
        path: configs/trino-coordinator/group-mapping.properties
      - name: group-provider.properties
        path: configs/trino-coordinator/group-provider.properties
      - name: jvm.config
        path: configs/trino-coordinator/jvm.config
      - name: log.properties
        path: configs/trino-coordinator/log.properties      
      - name: node.properties
        path: configs/trino-coordinator/node.properties
      - name: password-authenticator.properties
        path: configs/trino-coordinator/password-authenticator.properties
      - name: password.db
        path: configs/trino-coordinator/password.db

  schemas:
    data:

  keystore:
    data:
      - name: keystore.jks
        path: configs/keystores/keystore.jks

  keystorep12:
    data:
      - name: trino.p12
        path: configs/keystores/trino.p12

######################

trino-worker:

  replicaCount: 2

  image:
    repository: "quay.io/osclimate/trino"
    tag: "latest"
    pullPolicy: IfNotPresent

  strategy: 
    type: Recreate

  service:
    type: ClusterIP

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

  configmapEnv:
    data:
      TRINO_COORDINATOR_HOSTNAME: http://trino-coordinator.$(NAMESPACE).svc.cluster.local:8080

  secretEnv:
    data:
      AWS_ACCESS_KEY_ID: minioAdmin
      AWS_SECRET_KEY_ID: admin1234
      INTER_COMM_SHARED_SECRET: kzs71nsYBRr8cysT62zb6P+VT8YsVi/eASfNKUJkvPDce6aof6FLyM/0EDA8qK46P8sD2jXBTTe7cKX0MEqTS2UNZ7YdYWHUUoSG2nLgEryZbqlEkguYWs2dSSYkzv9DIPMtRvGxmNdQ6HGGscrqsFkeK7kSCd6mn5YNskIv6Z665gquqq+SlqV5UylFDcXhB6Z7oWuZ2fq3WONVWtTIhYP73YO8iDORG2afkqPQhRKTw848YQVrcqKAIOX6sirMb5KE1BP0yXz533J71vFuMqkvTBrFV3lkvAq+/7W4iA9Xn9WDJ8TGgcwB7jFOLH9htKYrXtO2XgMsWxizi7XbFzXsPEreqndhZEX7i6U0/K22kCWRy7/lcH+JMQAzq3J+qxl1KqTLVTfu3iSIKUj093/wR0EPcH282a+HMzk/5E1aGk3uV40M/1wQwlEDzBRaGtLtW7tyFHX+sc29nLgkOFAPknwqnYoSR7FDEgO+CrB00zNeY1lS1Xx8OCEfGgg+y5zK7pSMm7cuq8PHjENXCsWOY3xNkJLKsf9mWiWLZhxE1G6EQMG8WPz2r+DhBskTaoHaRPCfcD3/2vaDEjvfK/9kek94g00JcjJB9HQQe3tINmEBxkA8SjIWZe40kcPU0hbKqeA8WFzUgwsB/2KxFvTcPpRvNKseozZZxL/2Dlk=
    type: Opaque


  catalogs:
    data:
      - name: hive.properties
        path: configs/trino-catalog/hive.properties
      - name: iceberg.properties
        path: configs/trino-catalog/iceberg.properties
      - name: tpcds.properties
        path: configs/trino-catalog/tpcds.properties
      - name: tpch.properties
        path: configs/trino-catalog/tpch.properties

  configs:
    data:
      - name: config.properties
        path: configs/trino-worker/config.properties
      - name: exchange-manager.properties
        path: configs/trino-worker/exchange-manager.properties
      - name: jvm.config
        path: configs/trino-worker/jvm.config
      - name: log.properties
        path: configs/trino-worker/log.properties
      - name: node.properties
        path: configs/trino-worker/node.properties

  schemas:
    data:

######################