replicaCount: 1

image:
  repository: quay.io/zagaos/kafka-observ-testcase
  tag: new-topicconf
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 5089

route:
  enabled: true
  subdomainName: order-srv-3


configmapEnv:
  data:
    POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
    POSTGRES_USER: zaga
    POSTGRES_PASSWORD: zaga123$

kafka-srv:
  enabled: true
