{{- range .Values.kafkaTopics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels: 
    strimzi.io/cluster: telemetry
spec:
  replicas: 4
  config:
    retention.ms: 36000
    segment.bytes: 1073741824
---
{{- end }}
