replicaCount: 1

image:
  repository: quay.io/zagaos/order-vendor-sample:errortestcase-1
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 5089

route:
  enabled: true
  subdomainName: order-srv-1


configmapEnv:
  data:
    POSTGRES_PASSWORD: zaga123$
    POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
    POSTGRES_USER: zaga

order-srv:
  enabled: true
