replicaCount: 1
image:
  repository: quay.io/zagaos/zagaobserve-apm-keycloak
  tag: "feea355"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  subdomainName: apm-keycloak

apmKeycloak:
  enabled: true
