{{- if .Values.minio.enabled }}

apiVersion: route.openshift.io/v1
kind: Route

metadata:

  name: {{ .Chart.Name }}-web

  labels:
    app: {{ .Chart.Name }}

spec:

  subdomain: {{ .Values.route.subdomain }}-web
  path: /
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
  port:
    targetPort: web

  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

  wildcardPolicy: None

{{- end }}