apiVersion: v2
name: otel
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"


dependencies:
  - name: apm-collector
    version: "0.1.0"
    repository: "file://charts/apm-collector"
    condition: subcharts.apm-collector
    tags:
      - apm-collector

  - name: infra-otel
    version: "0.1.0"
    repository: "file://charts/infra-otel"
    condition: subcharts.infra-otel
    tags:
      - infra-collector

  - name: eventpower-collector
    version: "0.1.0"
    repository: "file://charts/eventpower-collector"
    condition: subcharts.eventpower-collector
    tags:
      - event-power

  - name: podpower-collector
    version: "0.1.0"
    repository: "file://charts/podpower-collector"
    condition: subcharts.podpower-collector
    tags:
      - pod-power

