order-srv-1:

  replicaCount: 1

  image:
    repository: quay.io/zagaos/order-vendor-sample:errortestcase-1
    pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    port: 5089

  route:
    enabled: true
    subdomainName: order-srv-1


  configmapEnv:
    data:
      POSTGRES_PASSWORD: zaga123$
      POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
      POSTGRES_USER: zaga

  order-srv:
    enabled: true

####################################################################

order-srv-2:

  replicaCount: 1

  image:
    repository: quay.io/zagaos/order-vendor-sample:order-test-2
    pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    port: 5089

  route:
    enabled: true
    subdomainName: order-srv-2


  configmapEnv:
    data:
      POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
      POSTGRES_USER: zaga
      POSTGRES_PASSWORD: zaga123$

  order-srv:
    enabled: true


#######################################################################

order-srv-3:

  replicaCount: 1

  image:
    repository: quay.io/zagaos/order-vendor-sample:order-test-3
    pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    port: 5089

  route:
    enabled: true
    subdomainName: order-srv-3


  configmapEnv:
    data:
      POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
      POSTGRES_USER: zaga
      POSTGRES_PASSWORD: zaga123$

  order-srv:
    enabled: true


###########################################################################################

vendor-srv-1:

  replicaCount: 1

  image:
    repository: quay.io/zagaos/order-vendor-sample
    tag: vendor-test-1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  route:
    enabled: true
    subdomainName: vendor-srv


  configmapEnv:
    data:
        POSTGRES_PASSWORD: zaga123$
        POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
        POSTGRES_USER: zaga
        APP_APIURL: http://order-srv.office-management.svc.cluster.local:5089/orders/getOrders
  vendor-srv:
    enabled: true


##################################################################################

vendor-srv-2:
  replicaCount: 1

  image:
    repository: quay.io/zagaos/order-vendor-sample
    tag: vendor-test-2
    pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    port: 8080

  route:
    enabled: true
    subdomainName: vendor-srv-2

  configmapEnv:
    data:
      data:
        POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
        POSTGRES_USER: zaga
        POSTGRES_PASSWORD: zaga123$
        APP_APIURL: http://order-srv-2.office-management.svc.cluster.local/orders/getOrders
  vendor-srv:
    enabled: true
############################################################################

vendor-srv-3:


  replicaCount: 1

  image:
    repository: quay.io/zagaos/order-vendor-sample:order-test-3
    pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    port: 5089

  route:
    enabled: true
    subdomainName: order-srv-3


  configmapEnv:
    data:
      POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
      POSTGRES_USER: zaga
      POSTGRES_PASSWORD: zaga123$

  order-srv:
    enabled: true



###################################################################################

kafka-srv:

  replicaCount: 1

  image:
    repository: quay.io/zagaos/kafka-observ-testcase
    tag: new-topicconf
    pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    port: 5089

  route:
    enabled: true
    subdomainName: order-srv-3


  configmapEnv:
    data:
      POSTGRES_URL: jdbc:postgresql://testcase-postgres.office-management.svc.cluster.local:5432/zagadb
      POSTGRES_USER: zaga
      POSTGRES_PASSWORD: zaga123$

  kafka-srv:
    enabled: true


#########################################################################
testcase-postgres:

  replicaCount: 1

  image:
    repository: "quay.io/osclimate/postgresql-13"
    tag: "1-101"

  strategy:
    type: {}

  service:
    type: ClusterIP

  securityContext: {}

  secretEnv:
    data:
      POSTGRESQL_USER: zaga
      POSTGRESQL_PASSWORD: zaga123$
      POSTGRESQL_DATABASE: zagadb
      POSTGRESQL_ADMIN_PASSWORD: zaga123$
    type: Opaque

  volumes:
    storageSize: 2Gi
    accessModes:
      - ReadWriteOnce

  postgres:
    enabled: true