{{- if .Values.kc.enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  
  {{- if .strategy }}
  strategy:
    type: {{ .Values.strategy.type }}
  {{- end }} 

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}

    spec:

      volumes:

        - name: {{ .Chart.Name }}-keystores-volume
          secret:
            secretName: {{ .Chart.Name }}-keystores-secret
            defaultMode: 420

        - name: {{ .Chart.Name }}-realms-volume
          configMap:
            name: {{ .Chart.Name }}-realms-configmap
            defaultMode: 420

      containers:
      - name: {{ .Chart.Name }}
        
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP

        {{- if .Values.probes.readiness }}
        readinessProbe:
          {{- toYaml .Values.probes.readiness | nindent 12 }}
        {{- end }}

        {{- if .Values.probes.liveness }}
        livenessProbe:
          {{- toYaml .Values.probes.liveness | nindent 12 }}
        {{- end }}


        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace

          - name: JAVA_OPTS_APPEND
            value: >-
              -Djgroups.dns.query={{ .Chart.Name }}-headless.$(NAMESPACE).svc.cluster.local

        envFrom:
          - secretRef:
              name: {{ .Chart.Name }}-admin-secret
          - secretRef:
              name: {{ .Chart.Name }}-postgres-secret

        args:
          - start
          # - '--import-realm'
          - '--hostname-strict=false'
          - '--https-certificate-file'
          - /etc/cert-volume/tls.crt
          - '--https-certificate-key-file'
          - /etc/cert-volume/tls.key
          - '--cache-stack'
          - kubernetes
          - '--db'
          - postgres
          - '--db-url'
          - >-
            jdbc:postgresql://$(POSTGRESQL_HOST).$(NAMESPACE).svc.cluster.local:$(POSTGRESQL_PORT)/$(POSTGRESQL_DB_NAME)
          - '--db-username'
          - '${POSTGRESQL_USER}'
          - '--db-password'
          - '${POSTGRESQL_PASSWORD}'
          - '--health-enabled'
          - 'true'
          - '--metrics-enabled'
          - 'true'
          - '--proxy'
          - reencrypt

        volumeMounts:
          
          - name: {{ .Chart.Name }}-keystores-volume
            readOnly: true
            mountPath: /etc/cert-volume

          - name: {{ .Chart.Name }}-realms-volume
            readOnly: true
            mountPath: /opt/keycloak/data/import

{{- end }}
