{{- if .Values.kc.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Chart.Name }}-admin-secret
  labels:
    app: {{ .Chart.Name }}

data:
{{- range $key, $value := .Values.adminSecret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}

type: {{ .Values.adminSecret.type }}