{{- $service := lookup "v1" "Service" .Release.Namespace .Chart.Name -}}
{{- if $service }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-keystores-secret
  labels:
    app: {{ .Chart.Name }}
  annotations:
    service.beta.openshift.io/originating-service-name: {{ .Chart.Name }}
    app.kubernetes.io/ownerreference: "true"
  ownerReferences:
    - apiVersion: v1
      kind: Service
      name: {{ .Chart.Name }}
      uid: {{ $service.metadata.uid | quote }}

data:
  {{- range .Values.keystores.data }}
    {{- if and .name .path }}
    {{ .name }}: |
      {{ $.Files.Get .path | b64enc | nindent 8 | trimSuffix "\n" }}
    {{- end }}
  {{- end }}

type: {{ .Values.keystores.type }}

{{- else }}

{{- end }}
