{{- if .Values.kc.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Chart.Name }}-keystores-secret
spec:
  ports:

  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443

  selector:
    app: {{ .Chart.Name }}

{{- end }}