replicaCount: 1

image:
  repository: quay.io/zagaos/zagaobserver-infra-ingestion
  tag: latest
  pullPolicy: IfNotPresent

configmapEnv:
  data:
    KAFKA_TOPIC: k8sevents
    SSL: "False"
    MINIO_BUCKET: observability-infra-events
    TABLE_NAME: event
    NAME_SPACE: infra_event
    CONSUMER_GROUP_ID: event_ingestion
    SCRIPT_TO_RUN: event
    BUCKET_NAME: s3a://observability-infra-events/events
    KAFKA_BOOTSTRAP_SERVER: 'telemetry-kafka-bootstrap.observability-kafka.svc.cluster.local:9092'
    URI: 'thrift://hive-metastore.observability-datamesh.svc.cluster.local:9083'
    S3_ENDPOINT: 'http://minio.observability-datamesh.svc.cluster.local:9000'
    ACCESS_KEY: minioAdmin
    SECRET_KEY: minio1234
  
ingestion:
  enabled: true