replicaCount: 1

image:
  repository: quay.io/zagaos/order-vendor-sample:order-test-3
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 5089

route:
  enabled: true
  subdomainName: order-srv-3


configmapEnv:
  data:
    POSTGRES_URL: jdbc:postgresql://testcase-postgres.observability-testcase.svc.cluster.local:5432/zagadb
    POSTGRES_USER: zaga
    POSTGRES_PASSWORD: zaga123$

order-srv:
  enabled: true
