{{- if .Values.worker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-catalogs
  labels:
    app: {{ .Chart.Name }}
data:
  {{- range .Values.catalogs.data }}
    {{- if and .name .path }}
    {{ .name }}: |
      {{ $.Files.Get .path | nindent 8 | trimSuffix "\n" }}
    {{- end }}
  {{- end }}
{{- end }}