replicaCount: 1
image:
  repository: quay.io/zagaos/zagaobserve-infra-keycloak
  tag: "feea355"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  subdomainName: infra-keycloak

infraKeycloak:
  enabled: true
