{{- if .Values.hivemetastoredb.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:

  - name: https
    protocol: TCP
    port: 5432
    targetPort: 5432

  selector:
    app: {{ .Chart.Name }}

{{- end }}