apiVersion: v2
name: sustainability
description: A Helm chart for Sustainability

version: 1.0.0

dependencies:

- name: sustain-ingestion-nodepowerlevel
  version: "1.0.0"
  repository: "file://charts/sustain-ingestion-nodepowerlevel"
  condition: subcharts.sustain-ingestion-nodepowerlevel
  tags:
  - sustain-ingestion-nodepowerlevel

- name: sustain-ingestion-podpowerlevel
  version: "1.0.0"
  repository: "file://charts/sustain-ingestion-podpowerlevel"
  condition: subcharts.sustain-ingestion-podpowerlevel
  tags:
  - sustain-ingestion-podpowerlevel

- name: sustain-query-api
  version: "1.0.0"
  repository: "file://charts/sustain-query-api"
  condition: subcharts.sustain-query-api
  tags:
  - sustain-query-api

- name: sustain-dashboard
  version: "1.0.0"
  repository: "file://charts/sustain-dashboard"
  condition: subcharts.sustain-dashboard
  tags:
  - sustain-dashboard
