apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-vendor-sample
  labels:
    app: order-vendor-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-vendor-sample
  template:
    metadata:
      labels:
        app: order-vendor-sample
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
    spec:
      imagePullSecrets: []
      serviceAccountName: ""
      securityContext: {}
      containers:
        - name: order-vendor-sample
          image: quay.io/zagaos/order-vendor-sample:errortestcase-1
          imagePullPolicy: IfNotPresent
          securityContext: {}
          ports:
            - name: http
              containerPort: 5089
              protocol: TCP
          envFrom:
            - configMapRef:
                name: order-vendor-sample-configmap
          readinessProbe:
            {}
          livenessProbe:
            {}
          resources: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
