replicaCount: 1

image:
  repository: "quay.io/osclimate/postgresql-13"
  tag: "1-101"

strategy:
  type: {}

service:
  type: ClusterIP

securityContext: {}

secretEnv:
  data:
    POSTGRESQL_ADMIN_PASSWORD: admin123$
    POSTGRESQL_DATABASE: hivemetadb
    POSTGRESQL_PASSWORD: hivemeta123$
    POSTGRESQL_USER: hive
  type: Opaque

volumes:
  storageSize: 2Gi
  accessModes:
    - ReadWriteOnce

hivemetastoredb:
  enabled: true