{{- if .Values.coordinator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
data:
{{- range $key, $value := .Values.secretEnv.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
type: {{ .Values.secretEnv.type }}