{{- if .Values.coordinator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-keystore
  labels:
    app: {{ .Chart.Name }}
data:
  {{- range .Values.keystore.data }}
    {{- if and .name .path }}
    {{ .name }}: |
      {{ $.Files.Get .path | b64enc | nindent 8 | trimSuffix "\n" }}
    {{- end }}
  {{- end }}
{{- end }}
type: Opaque