apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Chart.Name }}
spec:
  mode: {{ .Values.mode }}
  replicas: {{ .Values.replicas }}
  image: {{ .Values.image }}
  podDisruptionBudget:
    maxUnavailable: 1
  observability:
    metrics: {}
  config: 
    receivers:
      k8s_events:
        auth_type: serviceAccount
        namespaces: []
      otlp:
        protocols:
          grpc:
            endpoint: {{ .Values.receiver.grpcEndpoint }}
          http:
            endpoint: {{ .Values.receiver.httpEndpoint }}

    processors:
      batch:
      resourcedetection/openshift:
        detectors:
          - openshift

      
    exporters:
      debug:
        verbosity: detailed

      kafka/k8sevents:
        topic: {{ .Values.exporters.kafka.eventTopic }}
        brokers:
          - {{ .Values.exporters.kafka.brokers }}
        encoding: {{ .Values.exporters.kafka.encoding }}
        protocol_version: {{ .Values.exporters.kafka.version }}
        producer:
          max_message_bytes: {{ .Values.exporters.kafka.max_message_bytes}}

    service:
      pipelines:
        logs/k8s-events:
          receivers:
            - k8s_events
          processors:
            - batch
            - resourcedetection/openshift
          exporters:
          {{- if .Values.logExporter.enabled }}
            - kafka/k8sevents
            - debug
          {{- else }}
            - debug
          {{- end }}

####################################################################################
