replicaCount: 1

image:
  repository: "quay.io/osclimate/minio"
  tag: "latest"

strategy:
  type: {}

service:
  type: ClusterIP

securityContext: {}

route:
  subdomain: minio

secretEnv:
  data:
    MINIO_ACCESS_KEY: minio
    MINIO_ROOT_PASSWORD: minio1234
    MINIO_ROOT_USER: minioAdmin
    MINIO_SECRET_KEY: minio1234
  type: Opaque

configmapEnv:
  data:
    MINIO_TRACE: "true"
    MINIO_PROMETHEUS_AUTH_TYPE: public

s3ConnectionEnv:
  S3_BUCKET: zaga
  S3_HOST: minio
  S3_PORT: "9000"
  MINIO_ACCESS_KEY: minioAdmin
  MINIO_SECRET_KEY: minio1234


probes:
  readiness:
      httpGet:
        path: /minio/health/ready
        port: 9000
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10
  liveness:
      httpGet:
        path: /minio/health/live
        port: 9000
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10

volumes:
  storageSize: 200Gi
  accessModes:
    - ReadWriteOnce

minio:
  enabled: true